# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160217_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotepoll',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='date completed at'),
        ),
    ]
