# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160221_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotepoll',
            name='probe_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
